# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  vmImage: 'Rishi-CICD'

stages:
  - stage:
    displayName: Terraform Validate
    jobs:
      - job:
        steps:
          - task: CopyFiles@2
            displayName: Copying Files
            inputs:
              Contents: |
                **
              TargetFolder: '$(build.artifactstagingdirectory)/artifacts'

          - task: PublishBuildArtifacts@1
            displayName: Publishing Artifacts
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/artifacts'
              ArtifactName: 'drop'
              publishLocation: 'Container'